{ user, ... }:
{
  users.users.${user}.home = "/Users/${user}";
  system.primaryUser = user;
  system.stateVersion = 6;

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  programs.zsh.enable = true;

  homebrew = {
    enable = true;
    onActivation.autoUpdate = true;
    onActivation.cleanup = "zap";
    onActivation.upgrade = true;

    brews = [
      "abseil"
      "ada-url"
      "asciinema"
      "autoconf"
      "bash"
      "brotli"
      "c-ares"
      "ca-certificates"
      "cocoapods"
      "dav1d"
      "direnv"
      "docker-compose"
      "ffmpeg"
      "fmt"
      "fzf"
      "gcc"
      "gettext"
      "gh"
      "ghq"
      "git"
      "gmp"
      "gnupg"
      "gnutls"
      "go"
      "hdrhistogram_c"
      "icu4c@78"
      "isl"
      "krb5"
      "lame"
      "lazydocker"
      "lazygit"
      "libassuan"
      "libevent"
      "libgcrypt"
      "libgpg-error"
      "libidn2"
      "libksba"
      "libmpc"
      "libnghttp2"
      "libnghttp3"
      "libngtcp2"
      "libtasn1"
      "libunistring"
      "libusb"
      "libuv"
      "libvpx"
      "libyaml"
      "llhttp"
      "lpeg"
      "luajit"
      "luv"
      "lz4"
      "m4"
      "mpfr"
      "mysql"
      "ncurses"
      "neovim"
      "nettle"
      "nginx"
      "nkf"
      "node"
      "npth"
      "openssl@3"
      "opus"
      "p11-kit"
      "pcre2"
      "pinentry"
      "pkgconf"
      "protobuf"
      "readline"
      "ripgrep"
      "ruby"
      "ruby-build"
      "sdl2"
      "simdjson"
      "sqlite"
      "svt-av1"
      "tmux"
      "tree-sitter"
      "tree-sitter-cli"
      "unbound"
      "unibilium"
      "utf8proc"
      "uvwasi"
      "x264"
      "x265"
      "xz"
      "z"
      "zlib-ng-compat"
      "zoxide"
      "zstd"
    ];

    casks = [
      "android-commandlinetools"
      "brave-browser"
      "chatgpt-atlas"
      "codex"
      "codex-app"
      "coteditor"
      "discord"
      "docker"
      "docker-desktop"
      "font-blex-mono-nerd-font"
      "google-chrome"
      "microsoft-teams"
      "obsidian"
      "pgadmin4"
      "powershell"
      "scroll-reverser"
      "unity-hub"
      "visual-studio-code"
      "zoom"
    ];
  };
}
